### ISSUE TITLE
Create a CLI Command to generate Ingress artifacts

### ISSUE THREAD

**Issue by 6za** [6za/cluster-tools#1]
# Problem

Generate these files for new ingress routes for a k3d cluster ingress rules. 

```yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-server-2
  namespace: argo
spec:
  rules:
  - host: argo.demo.internal
    http:
      paths:
      - backend:
          service:
            name: argo-server
            port:
              number: 2746
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - argo.demo.internal
    secretName: argo-tls
```

# Solution

- [x] CLI that generate ingress artifacts for a list of applications, and commit them on a gitops repo. 

```bash 
cluster-tools -host-domain `demo.internal` -apps "atlantis,minio,minio-console,vault,chartmuseum,argo,argocd,kubefirst-console" -repo https://github.com/kubefirst/kubefirst.git --path registry
```
- It will create an ingress application and add to it the folder with the ingress alternative routes. 

# CLI Internals

- Generate artifacts based on parameters provided
- Commit new application to gitops repo
- Use a GITHUB_TOKEN env variable for it
